apiVersion: v1
kind: Pod
metadata:
  name: argocd-nginx
  labels:
    app.kubernetes.io/name: argocd-nginx
spec:
  containers:
  - name: nginx
    image: nginx
   
    ports:
      - containerPort: 80


